export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  AGENT_CLAIM_NOT_FOUND: "AGENT_CLAIM_NOT_FOUND",
  AGENT_ALREADY_CLAIMED: "AGENT_ALREADY_CLAIMED",
  AGENT_DISABLED: "AGENT_DISABLED",
  INVALID_CLAIM_CODE: "INVALID_CLAIM_CODE",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  ASSET_NOT_SUPPORTED: "ASSET_NOT_SUPPORTED",
  POLICY_VIOLATION: "POLICY_VIOLATION",
  INTENT_NOT_FOUND: "INTENT_NOT_FOUND",
  LOAN_NOT_FOUND: "LOAN_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  KNOWLEDGE_NOT_APPROVED: "KNOWLEDGE_NOT_APPROVED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
